FROM golang:alpine AS builder

RUN go env -w GOPROXY=https://goproxy.cn,https://goproxy.io,https://mirrors.aliyun.com/goproxy,direct
RUN go install tailscale.com/cmd/derper@main

FROM alpine:edge
WORKDIR /app

ENV DERP_DOMAIN=tossp.com
ENV DERP_CERT_MODE=manual
ENV DERP_CERT_DIR=/app/certs
ENV DERP_ADDR=:443
ENV DERP_STUN=true
ENV DERP_STUN_PORT=3478
ENV DERP_HTTP_PORT=80
ENV DERP_VERIFY_CLIENTS=false

COPY --from=builder /go/bin/derper .

# HEALTHCHECK --interval=3m --timeout=30s --start-period=10s --retries=3 CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:$DERP_HTTP_PORT

CMD /app/derper --hostname=$DERP_DOMAIN --certmode=$DERP_CERT_MODE --certdir=$DERP_CERT_DIR --a=$DERP_ADDR --stun=$DERP_STUN --stun-port=$DERP_STUN_PORT --http-port=$DERP_HTTP_PORT --verify-clients=$DERP_VERIFY_CLIENTS
