name: 镜像构建
on:
  # 任意推送都会触发构建
  push:
    paths:
      - '.github/workflows/composer.yml'
  schedule:
    - cron: "30 5 * * 5"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 准备环境变量
        id: prepare
        run: echo "today=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3
      - name: 设置 Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: 查看可用平台
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 GitHub 容器镜像
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 登录 DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 构建 hs-derp
        uses: docker/build-push-action@v5
        with:
          context: ./compose/hs-derp
          file: ./compose/hs-derp/dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tossp/hs-derp:latest
            tossp/hs-derp:${{ steps.prepare.outputs.today }}
      - name: 构建 jellyfin
        uses: docker/build-push-action@v5
        with:
          context: ./compose/jellyfin
          file: ./compose/jellyfin/dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tossp/jellyfin:latest
            tossp/jellyfin:${{ steps.prepare.outputs.today }}
      - name: 删除旧的工作流
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
