name: hs-derp 构建
on:
  # 任意推送都会触发构建
  push:
    paths:
      - "compose/hs-derp/dockerfile"
  schedule:
    - cron: "30 5 * * 5"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 准备环境变量
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2
      - name: 设置 Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: 查看可用平台
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: 登录 GitHub 容器镜像
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 登录 DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 构建并推送
        uses: docker/build-push-action@v3
        with:
          context: ./compose/hs-derp
          file: ./compose/hs-derp/dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tossp/hs-derp:latest
            tossp/hs-derp:${{ steps.date.outputs.today }}
      - name: 删除旧的工作流
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
