name: 镜像推送

# Controls when the action will run. 
on:
  # 任意推送都会触发构建
  push:
    paths:
      - '/.github/workflows/mirror.yml'
  # 定时调度
  # schedule:
  #   - cron: "30 5 * * 5"

  # Allows you to run this workflow manually from the Actions tab
# 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'   
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  buildx:
    runs-on: ubuntu-latest
    name: 推送镜像 "${{matrix.user}}/${{matrix.name}}:${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
       include:
         - user: dreamacro
           name: clash-premium           
           version: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: 查看可用平台
        run: echo ${{ steps.buildx.outputs.platforms }}
      # - name: 登录天坑容器
      #   uses: docker/login-action@v1
      #   with:
      #     registry: tsds.tossp.com:2087
      #     username: ${{ secrets.TOSSP_USERNAME }}
      #     password: ${{ secrets.TOSSP_PASSWORD }}
      - name: 推送
        run: |
          docker pull ${{matrix.user}}/${{matrix.name}}:${{matrix.version}}
          docker tag ${{matrix.user}}/${{matrix.name}}:${{matrix.version}} registry.tossp.com/ts/compiler/${{matrix.name}}:${{matrix.version}}
          # docker push tsds.tossp.com:2087/mirror/${{matrix.name}}:${{matrix.version}}
      - name: 删除旧的工作流
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
